// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/main/java/main/analizadores/lexico.jflex

package main.analizadores;

import java_cup.runtime.Symbol;
import java.util.LinkedList;
import main.excepciones.Errores;


@SuppressWarnings("fallthrough")
public class scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  2,  3,  2,  2,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     1,  4,  5,  0,  0,  0,  6,  0,  7,  8,  9, 10,  0, 11, 12, 13, 
    14, 15, 14, 14, 14, 14, 14, 14, 14, 14, 16, 17, 18, 19, 20,  0, 
     0, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 
    36, 30, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,  0, 49, 
     0, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 
    36, 30, 37, 38, 39, 40, 41, 42, 43, 44, 45, 50, 51, 52,  0,  0, 
     0,  0,  0,  0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\1\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\20\21\1\22\1\23\1\24\1\1\1\25"+
    "\1\0\1\26\1\21\1\0\1\27\1\0\22\21\1\30"+
    "\1\31\17\21\1\32\1\0\1\33\1\0\1\21\1\34"+
    "\1\35\15\21\1\36\5\21\1\37\21\21\1\40\7\21"+
    "\1\2\1\0\4\21\1\41\2\21\1\42\1\21\1\43"+
    "\1\21\1\44\1\21\1\45\13\21\1\46\1\47\1\50"+
    "\3\21\1\51\1\21\1\52\4\21\1\53\5\21\1\54"+
    "\2\21\1\55\1\56\1\57\2\21\1\0\4\21\1\60"+
    "\1\61\2\21\1\62\1\21\1\63\11\21\1\64\17\21"+
    "\1\65\1\66\1\0\4\21\1\67\1\21\1\70\1\21"+
    "\1\71\3\21\1\72\5\21\1\73\1\74\1\75\2\21"+
    "\1\76\3\21\1\77\1\21\1\100\2\21\1\2\2\21"+
    "\1\101\2\21\1\102\4\21\1\103\1\104\2\21\1\105"+
    "\2\21\1\106\1\21\1\107\5\21\1\110\1\111\1\21"+
    "\1\112\3\21\1\113\1\21\1\114\10\21\1\115\2\21"+
    "\1\116\1\117\1\120\2\21\1\121\2\21\1\122\1\21"+
    "\1\123\1\124\4\21\1\125\4\21\1\126";

  private static int [] zzUnpackAction() {
    int [] result = new int[327];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\65\0\152\0\237\0\65\0\324\0\65\0\65"+
    "\0\65\0\65\0\u0109\0\65\0\u013e\0\65\0\65\0\u0173"+
    "\0\65\0\65\0\u01a8\0\u01dd\0\u0212\0\u0247\0\u027c\0\u02b1"+
    "\0\u0109\0\u02e6\0\u031b\0\u0350\0\u0385\0\u03ba\0\u03ef\0\u0424"+
    "\0\u0459\0\u048e\0\65\0\65\0\65\0\u04c3\0\65\0\u04f8"+
    "\0\65\0\u052d\0\u0562\0\u0597\0\u05cc\0\u0601\0\u0636\0\u066b"+
    "\0\u06a0\0\u06d5\0\u070a\0\u073f\0\u0774\0\u07a9\0\u07de\0\u0813"+
    "\0\u0848\0\u087d\0\u08b2\0\u08e7\0\u091c\0\u0951\0\u0986\0\u0109"+
    "\0\u0109\0\u09bb\0\u09f0\0\u0a25\0\u0a5a\0\u0a8f\0\u0ac4\0\u0af9"+
    "\0\u0b2e\0\u0b63\0\u0b98\0\u0bcd\0\u0c02\0\u0c37\0\u0c6c\0\u0ca1"+
    "\0\65\0\u0cd6\0\u0562\0\u0d0b\0\u0d40\0\u0109\0\u0109\0\u0d75"+
    "\0\u0daa\0\u0ddf\0\u0e14\0\u0e49\0\u0e7e\0\u0eb3\0\u0ee8\0\u0f1d"+
    "\0\u0f52\0\u0f87\0\u0fbc\0\u0ff1\0\u0109\0\u1026\0\u105b\0\u1090"+
    "\0\u10c5\0\u10fa\0\u0109\0\u112f\0\u1164\0\u1199\0\u11ce\0\u1203"+
    "\0\u1238\0\u126d\0\u12a2\0\u12d7\0\u130c\0\u1341\0\u1376\0\u13ab"+
    "\0\u13e0\0\u1415\0\u144a\0\u147f\0\u0109\0\u14b4\0\u14e9\0\u151e"+
    "\0\u1553\0\u1588\0\u15bd\0\u15f2\0\u04f8\0\u1627\0\u165c\0\u1691"+
    "\0\u16c6\0\u16fb\0\u0109\0\u1730\0\u1765\0\u0109\0\u179a\0\u0109"+
    "\0\u17cf\0\u0109\0\u1804\0\u052d\0\u1839\0\u186e\0\u18a3\0\u18d8"+
    "\0\u190d\0\u1942\0\u1977\0\u19ac\0\u19e1\0\u1a16\0\u1a4b\0\u0109"+
    "\0\u0109\0\u0109\0\u1a80\0\u1ab5\0\u1aea\0\u0109\0\u1b1f\0\u0109"+
    "\0\u1b54\0\u1b89\0\u1bbe\0\u1bf3\0\u0109\0\u1c28\0\u1c5d\0\u1c92"+
    "\0\u1cc7\0\u1cfc\0\u0109\0\u1d31\0\u1d66\0\u1d9b\0\u0109\0\u0109"+
    "\0\u1dd0\0\u1e05\0\u1e3a\0\u1e6f\0\u1ea4\0\u1ed9\0\u1f0e\0\u0109"+
    "\0\u0109\0\u1f43\0\u1f78\0\u0109\0\u1fad\0\u0109\0\u1fe2\0\u2017"+
    "\0\u204c\0\u2081\0\u20b6\0\u20eb\0\u2120\0\u2155\0\u218a\0\u0109"+
    "\0\u21bf\0\u21f4\0\u2229\0\u225e\0\u2293\0\u22c8\0\u22fd\0\u2332"+
    "\0\u2367\0\u239c\0\u23d1\0\u2406\0\u243b\0\u2470\0\u24a5\0\u0109"+
    "\0\u0109\0\u24da\0\u250f\0\u2544\0\u2579\0\u25ae\0\u0109\0\u25e3"+
    "\0\u0109\0\u2618\0\u0109\0\u264d\0\u2682\0\u26b7\0\u0109\0\u26ec"+
    "\0\u2721\0\u2756\0\u278b\0\u27c0\0\u0109\0\u0109\0\u0109\0\u27f5"+
    "\0\u282a\0\u0109\0\u285f\0\u2894\0\u28c9\0\u0109\0\u28fe\0\u0109"+
    "\0\u2933\0\u2968\0\65\0\u299d\0\u29d2\0\u0109\0\u2a07\0\u2a3c"+
    "\0\u0109\0\u2a71\0\u2aa6\0\u2adb\0\u2b10\0\u0109\0\u0109\0\u2b45"+
    "\0\u2b7a\0\u0109\0\u2baf\0\u2be4\0\u0109\0\u2c19\0\u0109\0\u2c4e"+
    "\0\u2c83\0\u2cb8\0\u2ced\0\u2d22\0\u0109\0\u0109\0\u2d57\0\u0109"+
    "\0\u2d8c\0\u2dc1\0\u2df6\0\u0109\0\u2e2b\0\u0109\0\u2e60\0\u2e95"+
    "\0\u2eca\0\u2eff\0\u2f34\0\u2f69\0\u2f9e\0\u2fd3\0\u0109\0\u3008"+
    "\0\u303d\0\u0109\0\u0109\0\u0109\0\u3072\0\u30a7\0\u0109\0\u30dc"+
    "\0\u3111\0\u0109\0\u3146\0\u0109\0\u0109\0\u317b\0\u31b0\0\u31e5"+
    "\0\u321a\0\u0109\0\u324f\0\u3284\0\u32b9\0\u32ee\0\u0109";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[327];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\2\1\14\2\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\2\31\1\34\1\31\1\35"+
    "\1\36\1\31\1\37\1\40\1\41\2\31\1\42\3\31"+
    "\1\43\1\2\1\44\1\31\1\45\1\46\1\47\66\0"+
    "\2\3\66\0\1\50\66\0\1\51\71\0\1\31\2\0"+
    "\2\52\5\0\31\31\3\0\1\31\17\0\1\53\1\0"+
    "\2\15\5\0\31\54\3\0\1\54\7\0\1\55\73\0"+
    "\1\31\2\0\2\52\5\0\13\31\1\56\5\31\1\57"+
    "\7\31\3\0\1\31\16\0\1\31\2\0\2\52\5\0"+
    "\1\60\15\31\1\61\12\31\3\0\1\31\16\0\1\31"+
    "\2\0\2\52\5\0\1\62\6\31\1\63\3\31\1\64"+
    "\2\31\1\65\12\31\3\0\1\66\16\0\1\31\2\0"+
    "\2\52\5\0\4\31\1\67\24\31\3\0\1\31\16\0"+
    "\1\31\2\0\2\52\5\0\13\31\1\70\1\31\1\71"+
    "\10\31\1\72\2\31\3\0\1\31\16\0\1\31\2\0"+
    "\2\52\5\0\1\73\15\31\1\74\12\31\3\0\1\31"+
    "\16\0\1\31\2\0\2\52\5\0\4\31\1\75\13\31"+
    "\1\76\2\31\1\77\5\31\3\0\1\31\16\0\1\31"+
    "\2\0\2\52\5\0\3\31\1\100\1\31\1\101\7\31"+
    "\1\102\13\31\3\0\1\31\16\0\1\31\2\0\2\52"+
    "\5\0\4\31\1\103\24\31\3\0\1\31\16\0\1\31"+
    "\2\0\2\52\5\0\1\104\22\31\1\105\5\31\3\0"+
    "\1\31\16\0\1\31\2\0\2\52\5\0\15\31\1\106"+
    "\13\31\3\0\1\31\16\0\1\31\2\0\2\52\5\0"+
    "\4\31\1\107\11\31\1\110\12\31\3\0\1\31\16\0"+
    "\1\31\2\0\2\52\5\0\20\31\1\111\1\31\1\112"+
    "\6\31\3\0\1\31\16\0\1\31\2\0\2\52\5\0"+
    "\4\31\1\113\2\31\1\114\10\31\1\115\6\31\1\116"+
    "\1\31\3\0\1\31\16\0\1\31\2\0\2\52\5\0"+
    "\7\31\1\117\1\120\20\31\3\0\1\31\66\0\1\121"+
    "\1\0\2\50\2\0\53\50\1\122\5\50\16\0\2\52"+
    "\5\0\31\52\3\0\1\52\21\0\2\123\63\0\2\54"+
    "\5\0\31\54\3\0\1\54\16\0\1\124\64\0\1\31"+
    "\2\0\2\52\5\0\4\31\1\125\15\31\1\126\6\31"+
    "\3\0\1\31\16\0\1\31\2\0\2\52\5\0\2\31"+
    "\1\127\26\31\3\0\1\31\16\0\1\31\2\0\2\52"+
    "\5\0\2\31\1\130\26\31\3\0\1\31\16\0\1\31"+
    "\2\0\2\52\5\0\16\31\1\131\12\31\3\0\1\31"+
    "\16\0\1\31\2\0\2\52\5\0\20\31\1\132\10\31"+
    "\3\0\1\31\16\0\1\31\2\0\2\52\5\0\1\133"+
    "\30\31\3\0\1\31\16\0\1\31\2\0\2\52\5\0"+
    "\1\134\30\31\3\0\1\31\16\0\1\31\2\0\2\52"+
    "\5\0\13\31\1\135\15\31\3\0\1\31\16\0\1\31"+
    "\2\0\2\52\5\0\1\31\1\136\1\137\1\140\3\31"+
    "\1\141\1\142\2\31\1\143\2\31\1\144\1\145\1\31"+
    "\1\146\1\147\6\31\3\0\1\31\16\0\1\31\2\0"+
    "\2\52\5\0\2\31\1\150\16\31\1\151\7\31\3\0"+
    "\1\31\16\0\1\31\2\0\2\52\5\0\21\31\1\152"+
    "\7\31\3\0\1\31\16\0\1\31\2\0\2\52\5\0"+
    "\3\31\1\153\25\31\3\0\1\31\16\0\1\31\2\0"+
    "\2\52\5\0\10\31\1\154\20\31\3\0\1\31\16\0"+
    "\1\31\2\0\2\52\5\0\13\31\1\155\15\31\3\0"+
    "\1\31\16\0\1\31\2\0\2\52\5\0\15\31\1\156"+
    "\13\31\3\0\1\31\16\0\1\31\2\0\2\52\5\0"+
    "\10\31\1\157\20\31\3\0\1\31\16\0\1\31\2\0"+
    "\2\52\5\0\4\31\1\160\24\31\3\0\1\31\16\0"+
    "\1\31\2\0\2\52\5\0\15\31\1\161\13\31\3\0"+
    "\1\31\16\0\1\31\2\0\2\52\5\0\10\31\1\162"+
    "\10\31\1\163\1\164\6\31\3\0\1\31\16\0\1\31"+
    "\2\0\2\52\5\0\22\31\1\165\6\31\3\0\1\31"+
    "\16\0\1\31\2\0\2\52\5\0\14\31\1\166\14\31"+
    "\3\0\1\31\16\0\1\31\2\0\2\52\5\0\14\31"+
    "\1\167\14\31\3\0\1\31\16\0\1\31\2\0\2\52"+
    "\5\0\2\31\1\170\26\31\3\0\1\31\16\0\1\31"+
    "\2\0\2\52\5\0\3\31\1\171\13\31\1\172\4\31"+
    "\1\173\4\31\3\0\1\31\16\0\1\31\2\0\2\52"+
    "\5\0\25\31\1\174\3\31\3\0\1\31\16\0\1\31"+
    "\2\0\2\52\5\0\2\31\1\175\26\31\3\0\1\31"+
    "\16\0\1\31\2\0\2\52\5\0\20\31\1\176\10\31"+
    "\3\0\1\31\16\0\1\31\2\0\2\52\5\0\26\31"+
    "\1\177\2\31\3\0\1\31\16\0\1\31\2\0\2\52"+
    "\5\0\4\31\1\200\24\31\3\0\1\31\16\0\1\31"+
    "\2\0\2\52\5\0\23\31\1\201\5\31\3\0\1\31"+
    "\16\0\1\31\2\0\2\52\5\0\17\31\1\202\11\31"+
    "\3\0\1\31\16\0\1\31\2\0\2\52\5\0\10\31"+
    "\1\203\20\31\3\0\1\31\16\0\1\31\2\0\2\52"+
    "\5\0\3\31\1\204\25\31\3\0\1\31\3\0\2\50"+
    "\2\0\36\50\1\205\14\50\1\122\5\50\13\0\1\206"+
    "\64\0\1\31\2\0\2\52\5\0\20\31\1\207\10\31"+
    "\3\0\1\31\16\0\1\31\2\0\2\52\5\0\12\31"+
    "\1\210\16\31\3\0\1\31\16\0\1\31\2\0\2\52"+
    "\5\0\13\31\1\211\15\31\3\0\1\31\16\0\1\31"+
    "\2\0\2\52\5\0\1\212\30\31\3\0\1\31\16\0"+
    "\1\31\2\0\2\52\5\0\20\31\1\213\10\31\3\0"+
    "\1\31\16\0\1\31\2\0\2\52\5\0\21\31\1\214"+
    "\7\31\3\0\1\31\16\0\1\31\2\0\2\52\5\0"+
    "\16\31\1\215\2\31\1\216\7\31\3\0\1\31\16\0"+
    "\1\31\2\0\2\52\5\0\16\31\1\217\1\31\1\220"+
    "\2\31\1\221\5\31\3\0\1\31\16\0\1\31\2\0"+
    "\2\52\5\0\2\31\1\222\26\31\3\0\1\31\16\0"+
    "\1\31\2\0\2\52\5\0\10\31\1\223\20\31\3\0"+
    "\1\31\16\0\1\31\2\0\1\52\1\224\5\0\4\31"+
    "\1\225\24\31\3\0\1\31\16\0\1\31\2\0\2\52"+
    "\5\0\14\31\1\226\1\227\13\31\3\0\1\31\16\0"+
    "\1\31\2\0\2\52\5\0\10\31\1\230\20\31\3\0"+
    "\1\31\16\0\1\31\2\0\2\52\5\0\17\31\1\231"+
    "\11\31\3\0\1\31\16\0\1\31\2\0\2\52\5\0"+
    "\2\31\1\232\1\31\1\233\12\31\1\234\11\31\3\0"+
    "\1\31\16\0\1\31\2\0\2\52\5\0\4\31\1\235"+
    "\3\31\1\236\20\31\3\0\1\31\16\0\1\31\2\0"+
    "\2\52\5\0\10\31\1\237\20\31\3\0\1\31\16\0"+
    "\1\31\2\0\2\52\5\0\2\31\1\240\26\31\3\0"+
    "\1\31\16\0\1\31\2\0\2\52\5\0\4\31\1\241"+
    "\24\31\3\0\1\31\16\0\1\31\2\0\2\52\5\0"+
    "\22\31\1\242\6\31\3\0\1\31\16\0\1\31\2\0"+
    "\2\52\5\0\21\31\1\243\7\31\3\0\1\31\16\0"+
    "\1\31\2\0\2\52\5\0\22\31\1\244\6\31\3\0"+
    "\1\31\16\0\1\31\2\0\2\52\5\0\6\31\1\245"+
    "\22\31\3\0\1\31\16\0\1\31\2\0\2\52\5\0"+
    "\5\31\1\246\23\31\3\0\1\31\16\0\1\31\2\0"+
    "\2\52\5\0\22\31\1\247\6\31\3\0\1\31\16\0"+
    "\1\31\2\0\2\52\5\0\22\31\1\250\6\31\3\0"+
    "\1\31\16\0\1\31\2\0\2\52\5\0\4\31\1\251"+
    "\24\31\3\0\1\31\16\0\1\31\2\0\2\52\5\0"+
    "\4\31\1\252\24\31\3\0\1\31\16\0\1\31\2\0"+
    "\2\52\5\0\10\31\1\253\6\31\1\254\11\31\3\0"+
    "\1\31\16\0\1\31\2\0\2\52\5\0\4\31\1\255"+
    "\24\31\3\0\1\31\16\0\1\31\2\0\2\52\5\0"+
    "\31\31\3\0\1\256\16\0\1\31\2\0\2\52\5\0"+
    "\13\31\1\257\15\31\3\0\1\31\16\0\1\31\2\0"+
    "\2\52\5\0\10\31\1\260\20\31\3\0\1\31\16\0"+
    "\1\31\2\0\2\52\5\0\4\31\1\261\24\31\3\0"+
    "\1\31\16\0\1\31\2\0\2\52\5\0\4\31\1\262"+
    "\24\31\3\0\1\31\16\0\1\31\2\0\2\52\5\0"+
    "\21\31\1\263\7\31\3\0\1\31\16\0\1\31\2\0"+
    "\2\52\5\0\10\31\1\264\20\31\3\0\1\31\16\0"+
    "\1\31\2\0\2\52\5\0\22\31\1\265\6\31\3\0"+
    "\1\31\16\0\1\31\2\0\2\52\5\0\15\31\1\266"+
    "\13\31\3\0\1\31\16\0\1\31\2\0\2\52\5\0"+
    "\4\31\1\267\24\31\3\0\1\31\16\0\1\31\2\0"+
    "\2\52\5\0\4\31\1\270\24\31\3\0\1\31\16\0"+
    "\1\31\2\0\2\52\5\0\13\31\1\271\15\31\3\0"+
    "\1\31\16\0\1\31\2\0\2\52\5\0\22\31\1\272"+
    "\6\31\3\0\1\31\3\0\13\206\1\273\10\206\1\0"+
    "\40\206\13\0\1\31\2\0\2\52\5\0\22\31\1\274"+
    "\6\31\3\0\1\31\16\0\1\31\2\0\2\52\5\0"+
    "\6\31\1\275\22\31\3\0\1\31\16\0\1\31\2\0"+
    "\2\52\5\0\4\31\1\276\24\31\3\0\1\31\16\0"+
    "\1\31\2\0\2\52\5\0\2\31\1\277\26\31\3\0"+
    "\1\31\16\0\1\31\2\0\2\52\5\0\21\31\1\300"+
    "\7\31\3\0\1\31\16\0\1\31\2\0\2\52\5\0"+
    "\20\31\1\301\10\31\3\0\1\31\16\0\1\31\2\0"+
    "\2\52\5\0\3\31\1\302\25\31\3\0\1\31\16\0"+
    "\1\31\2\0\2\52\5\0\22\31\1\303\6\31\3\0"+
    "\1\31\16\0\1\31\2\0\2\52\5\0\24\31\1\304"+
    "\4\31\3\0\1\31\16\0\1\31\2\0\2\52\5\0"+
    "\1\305\30\31\3\0\1\31\16\0\1\31\2\0\2\52"+
    "\5\0\6\31\1\306\22\31\3\0\1\31\16\0\1\31"+
    "\2\0\2\52\5\0\17\31\1\307\11\31\3\0\1\31"+
    "\16\0\1\31\2\0\2\52\5\0\15\31\1\310\13\31"+
    "\3\0\1\31\16\0\1\31\2\0\2\52\5\0\22\31"+
    "\1\311\6\31\3\0\1\31\16\0\1\31\2\0\2\52"+
    "\5\0\20\31\1\312\10\31\3\0\1\31\16\0\1\31"+
    "\2\0\2\52\5\0\13\31\1\313\15\31\3\0\1\31"+
    "\16\0\1\31\2\0\2\52\5\0\1\314\30\31\3\0"+
    "\1\31\16\0\1\31\2\0\2\52\5\0\26\31\1\315"+
    "\2\31\3\0\1\31\16\0\1\31\2\0\2\52\5\0"+
    "\22\31\1\316\6\31\3\0\1\31\16\0\1\31\2\0"+
    "\2\52\5\0\14\31\1\317\14\31\3\0\1\31\16\0"+
    "\1\31\2\0\2\52\5\0\4\31\1\320\24\31\3\0"+
    "\1\31\16\0\1\321\2\0\2\52\5\0\31\31\3\0"+
    "\1\31\16\0\1\31\2\0\2\52\5\0\7\31\1\322"+
    "\21\31\3\0\1\31\16\0\1\31\2\0\2\52\5\0"+
    "\10\31\1\323\20\31\3\0\1\31\16\0\1\31\2\0"+
    "\2\52\5\0\20\31\1\324\10\31\3\0\1\31\16\0"+
    "\1\31\2\0\2\52\5\0\6\31\1\325\22\31\3\0"+
    "\1\31\16\0\1\31\2\0\2\52\5\0\14\31\1\326"+
    "\14\31\3\0\1\31\16\0\1\31\2\0\2\52\5\0"+
    "\1\327\30\31\3\0\1\31\16\0\1\31\2\0\2\52"+
    "\5\0\1\330\30\31\3\0\1\31\16\0\1\31\2\0"+
    "\2\52\5\0\10\31\1\331\20\31\3\0\1\31\16\0"+
    "\1\31\2\0\2\52\5\0\20\31\1\332\10\31\3\0"+
    "\1\31\16\0\1\31\2\0\2\52\5\0\1\333\30\31"+
    "\3\0\1\31\16\0\1\31\2\0\2\52\5\0\20\31"+
    "\1\334\10\31\3\0\1\31\16\0\1\31\2\0\2\52"+
    "\5\0\15\31\1\335\13\31\3\0\1\31\16\0\1\336"+
    "\2\0\2\52\5\0\31\31\3\0\1\31\16\0\1\31"+
    "\2\0\2\52\5\0\25\31\1\337\3\31\3\0\1\31"+
    "\16\0\1\31\2\0\2\52\5\0\4\31\1\340\24\31"+
    "\3\0\1\31\16\0\1\31\2\0\2\52\5\0\7\31"+
    "\1\341\21\31\3\0\1\31\3\0\13\206\1\342\10\206"+
    "\1\0\40\206\13\0\1\31\2\0\2\52\5\0\31\31"+
    "\3\0\1\343\16\0\1\31\2\0\2\52\5\0\20\31"+
    "\1\344\10\31\3\0\1\31\16\0\1\31\2\0\2\52"+
    "\5\0\1\345\30\31\3\0\1\31\16\0\1\31\2\0"+
    "\2\52\5\0\22\31\1\346\6\31\3\0\1\31\16\0"+
    "\1\31\2\0\2\52\5\0\27\31\1\347\1\31\3\0"+
    "\1\31\16\0\1\31\2\0\2\52\5\0\22\31\1\350"+
    "\6\31\3\0\1\31\16\0\1\31\2\0\2\52\5\0"+
    "\3\31\1\351\25\31\3\0\1\31\16\0\1\31\2\0"+
    "\2\52\5\0\23\31\1\352\5\31\3\0\1\31\16\0"+
    "\1\31\2\0\2\52\5\0\12\31\1\353\16\31\3\0"+
    "\1\31\16\0\1\31\2\0\2\52\5\0\10\31\1\354"+
    "\20\31\3\0\1\31\16\0\1\31\2\0\2\52\5\0"+
    "\10\31\1\355\20\31\3\0\1\31\16\0\1\31\2\0"+
    "\2\52\5\0\4\31\1\356\24\31\3\0\1\31\16\0"+
    "\1\31\2\0\2\52\5\0\14\31\1\357\14\31\3\0"+
    "\1\31\16\0\1\31\2\0\2\52\5\0\22\31\1\360"+
    "\6\31\3\0\1\31\16\0\1\31\2\0\2\52\5\0"+
    "\13\31\1\361\15\31\3\0\1\31\16\0\1\31\2\0"+
    "\2\52\5\0\1\362\30\31\3\0\1\31\16\0\1\31"+
    "\2\0\2\52\5\0\5\31\1\363\13\31\1\364\7\31"+
    "\3\0\1\31\16\0\1\31\2\0\2\52\5\0\22\31"+
    "\1\365\6\31\3\0\1\31\16\0\1\31\2\0\2\52"+
    "\5\0\13\31\1\366\15\31\3\0\1\31\16\0\1\31"+
    "\2\0\2\52\5\0\22\31\1\367\6\31\3\0\1\31"+
    "\16\0\1\31\2\0\2\52\5\0\4\31\1\370\24\31"+
    "\3\0\1\31\16\0\1\31\2\0\2\52\5\0\17\31"+
    "\1\371\11\31\3\0\1\31\16\0\1\31\2\0\2\52"+
    "\5\0\20\31\1\372\10\31\3\0\1\31\16\0\1\31"+
    "\2\0\2\52\5\0\13\31\1\373\15\31\3\0\1\31"+
    "\16\0\1\31\2\0\2\52\5\0\2\31\1\374\26\31"+
    "\3\0\1\31\16\0\1\31\2\0\2\52\5\0\4\31"+
    "\1\375\24\31\3\0\1\31\16\0\1\31\2\0\2\52"+
    "\5\0\22\31\1\376\6\31\3\0\1\31\16\0\1\31"+
    "\2\0\2\52\5\0\21\31\1\377\7\31\3\0\1\31"+
    "\16\0\1\31\2\0\2\52\5\0\6\31\1\u0100\22\31"+
    "\3\0\1\31\16\0\1\31\2\0\2\52\5\0\1\u0101"+
    "\30\31\3\0\1\31\16\0\1\31\2\0\2\52\5\0"+
    "\7\31\1\u0102\21\31\3\0\1\31\3\0\13\206\1\342"+
    "\10\206\1\u0103\40\206\13\0\1\31\2\0\2\52\5\0"+
    "\10\31\1\u0104\20\31\3\0\1\31\16\0\1\31\2\0"+
    "\2\52\5\0\16\31\1\u0105\12\31\3\0\1\31\16\0"+
    "\1\31\2\0\2\52\5\0\15\31\1\u0106\13\31\3\0"+
    "\1\31\16\0\1\31\2\0\2\52\5\0\4\31\1\u0107"+
    "\24\31\3\0\1\31\16\0\1\31\2\0\2\52\5\0"+
    "\16\31\1\u0108\12\31\3\0\1\31\16\0\1\31\2\0"+
    "\2\52\5\0\22\31\1\u0109\6\31\3\0\1\31\16\0"+
    "\1\31\2\0\2\52\5\0\16\31\1\u010a\12\31\3\0"+
    "\1\31\16\0\1\31\2\0\2\52\5\0\17\31\1\u010b"+
    "\11\31\3\0\1\31\16\0\1\31\2\0\2\52\5\0"+
    "\2\31\1\u010c\26\31\3\0\1\31\16\0\1\31\2\0"+
    "\2\52\5\0\1\u010d\30\31\3\0\1\31\16\0\1\31"+
    "\2\0\2\52\5\0\4\31\1\u010e\24\31\3\0\1\31"+
    "\16\0\1\31\2\0\2\52\5\0\13\31\1\u010f\15\31"+
    "\3\0\1\31\16\0\1\31\2\0\2\52\5\0\1\u0110"+
    "\30\31\3\0\1\31\16\0\1\31\2\0\2\52\5\0"+
    "\10\31\1\u0111\20\31\3\0\1\31\16\0\1\31\2\0"+
    "\2\52\5\0\20\31\1\u0112\10\31\3\0\1\31\16\0"+
    "\1\31\2\0\2\52\5\0\1\u0113\30\31\3\0\1\31"+
    "\16\0\1\31\2\0\2\52\5\0\4\31\1\u0114\24\31"+
    "\3\0\1\31\16\0\1\31\2\0\2\52\5\0\12\31"+
    "\1\u0115\16\31\3\0\1\31\16\0\1\31\2\0\2\52"+
    "\5\0\2\31\1\u0116\26\31\3\0\1\31\16\0\1\31"+
    "\2\0\2\52\5\0\4\31\1\u0117\24\31\3\0\1\31"+
    "\16\0\1\31\2\0\2\52\5\0\13\31\1\u0118\15\31"+
    "\3\0\1\31\16\0\1\31\2\0\2\52\5\0\10\31"+
    "\1\u0119\20\31\3\0\1\31\16\0\1\31\2\0\2\52"+
    "\5\0\15\31\1\u011a\13\31\3\0\1\31\16\0\1\31"+
    "\2\0\2\52\5\0\23\31\1\u011b\5\31\3\0\1\31"+
    "\16\0\1\31\2\0\2\52\5\0\20\31\1\u011c\10\31"+
    "\3\0\1\31\16\0\1\31\2\0\2\52\5\0\15\31"+
    "\1\u011d\13\31\3\0\1\31\16\0\1\31\2\0\2\52"+
    "\5\0\15\31\1\u011e\13\31\3\0\1\31\16\0\1\31"+
    "\2\0\2\52\5\0\22\31\1\u011f\6\31\3\0\1\31"+
    "\16\0\1\31\2\0\2\52\5\0\22\31\1\u0120\6\31"+
    "\3\0\1\31\16\0\1\31\2\0\2\52\5\0\20\31"+
    "\1\u0121\10\31\3\0\1\31\16\0\1\31\2\0\2\52"+
    "\5\0\14\31\1\u0122\14\31\3\0\1\31\16\0\1\31"+
    "\2\0\2\52\5\0\30\31\1\u0123\3\0\1\31\16\0"+
    "\1\31\2\0\2\52\5\0\20\31\1\u0124\10\31\3\0"+
    "\1\31\16\0\1\31\2\0\2\52\5\0\1\u0125\30\31"+
    "\3\0\1\31\16\0\1\31\2\0\2\52\5\0\22\31"+
    "\1\u0126\6\31\3\0\1\31\16\0\1\31\2\0\2\52"+
    "\5\0\10\31\1\u0127\20\31\3\0\1\31\16\0\1\31"+
    "\2\0\2\52\5\0\13\31\1\u0128\15\31\3\0\1\31"+
    "\16\0\1\31\2\0\2\52\5\0\5\31\1\u0129\23\31"+
    "\3\0\1\31\16\0\1\31\2\0\2\52\5\0\15\31"+
    "\1\u012a\13\31\3\0\1\31\16\0\1\31\2\0\2\52"+
    "\5\0\31\31\3\0\1\u012b\16\0\1\31\2\0\2\52"+
    "\5\0\10\31\1\u012c\20\31\3\0\1\31\16\0\1\31"+
    "\2\0\2\52\5\0\4\31\1\u012d\24\31\3\0\1\31"+
    "\16\0\1\31\2\0\2\52\5\0\10\31\1\u012e\20\31"+
    "\3\0\1\31\16\0\1\31\2\0\2\52\5\0\4\31"+
    "\1\u012f\24\31\3\0\1\31\16\0\1\31\2\0\2\52"+
    "\5\0\22\31\1\u0130\6\31\3\0\1\31\16\0\1\31"+
    "\2\0\2\52\5\0\6\31\1\u0131\22\31\3\0\1\31"+
    "\16\0\1\31\2\0\2\52\5\0\4\31\1\u0132\24\31"+
    "\3\0\1\31\16\0\1\31\2\0\2\52\5\0\16\31"+
    "\1\u0133\12\31\3\0\1\31\16\0\1\31\2\0\2\52"+
    "\5\0\3\31\1\u0134\25\31\3\0\1\31\16\0\1\31"+
    "\2\0\2\52\5\0\1\u0135\30\31\3\0\1\31\16\0"+
    "\1\31\2\0\2\52\5\0\15\31\1\u0136\13\31\3\0"+
    "\1\31\16\0\1\31\2\0\2\52\5\0\1\u0137\30\31"+
    "\3\0\1\31\16\0\1\31\2\0\2\52\5\0\13\31"+
    "\1\u0138\15\31\3\0\1\31\16\0\1\31\2\0\2\52"+
    "\5\0\16\31\1\u0139\12\31\3\0\1\31\16\0\1\31"+
    "\2\0\2\52\5\0\15\31\1\u013a\13\31\3\0\1\31"+
    "\16\0\1\31\2\0\2\52\5\0\13\31\1\u013b\15\31"+
    "\3\0\1\31\16\0\1\31\2\0\2\52\5\0\6\31"+
    "\1\u013c\22\31\3\0\1\31\16\0\1\31\2\0\2\52"+
    "\5\0\27\31\1\u013d\1\31\3\0\1\31\16\0\1\31"+
    "\2\0\2\52\5\0\20\31\1\u013e\10\31\3\0\1\31"+
    "\16\0\1\31\2\0\2\52\5\0\4\31\1\u013f\24\31"+
    "\3\0\1\31\16\0\1\31\2\0\2\52\5\0\10\31"+
    "\1\u0140\20\31\3\0\1\31\16\0\1\31\2\0\2\52"+
    "\5\0\1\u0141\30\31\3\0\1\31\16\0\1\31\2\0"+
    "\2\52\5\0\16\31\1\u0142\12\31\3\0\1\31\16\0"+
    "\1\31\2\0\2\52\5\0\22\31\1\u0143\6\31\3\0"+
    "\1\31\16\0\1\31\2\0\2\52\5\0\16\31\1\u0144"+
    "\12\31\3\0\1\31\16\0\1\31\2\0\2\52\5\0"+
    "\20\31\1\u0145\10\31\3\0\1\31\16\0\1\31\2\0"+
    "\2\52\5\0\10\31\1\u0146\20\31\3\0\1\31\16\0"+
    "\1\31\2\0\2\52\5\0\16\31\1\u0147\12\31\3\0"+
    "\1\31\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[13091];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\1\1\4\11\1\1\1\11"+
    "\1\1\2\11\1\1\2\11\20\1\3\11\1\1\1\11"+
    "\1\0\1\11\1\1\1\0\1\1\1\0\43\1\1\11"+
    "\1\0\1\1\1\0\61\1\1\0\64\1\1\0\46\1"+
    "\1\0\40\1\1\11\104\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[327];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    public LinkedList<Errores> listaErrores = new LinkedList<>();

    public LinkedList<Errores> getErrores(){
        return listaErrores;
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public scanner(java.io.Reader in) {
      yyline = 1;
    yycolumn = 1;
    listaErrores = new LinkedList<>();
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    return ZZ_CMAP[input];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { listaErrores.add(new Errores("LEXICO","El caracter "+
                yytext() + " No pertenece al lenguaje", yyline, yycolumn, "Eliminar Caracter: "+ yytext()));
            }
          // fall through
          case 87: break;
          case 2:
            { 
            }
          // fall through
          case 88: break;
          case 3:
            { return new Symbol(sym.DIFER, yyline, yycolumn,yytext());
            }
          // fall through
          case 89: break;
          case 4:
            { return new Symbol(sym.COMID, yyline, yycolumn,yytext());
            }
          // fall through
          case 90: break;
          case 5:
            { return new Symbol(sym.PAR1, yyline, yycolumn,yytext());
            }
          // fall through
          case 91: break;
          case 6:
            { return new Symbol(sym.PAR2, yyline, yycolumn,yytext());
            }
          // fall through
          case 92: break;
          case 7:
            { return new Symbol(sym.POR, yyline, yycolumn,yytext());
            }
          // fall through
          case 93: break;
          case 8:
            { return new Symbol(sym.MAS, yyline, yycolumn,yytext());
            }
          // fall through
          case 94: break;
          case 9:
            { return new Symbol(sym.MENOS, yyline, yycolumn,yytext());
            }
          // fall through
          case 95: break;
          case 10:
            { return new Symbol(sym.DIVI, yyline, yycolumn,yytext());
            }
          // fall through
          case 96: break;
          case 11:
            { return new Symbol(sym.ENTERO, yyline, yycolumn,yytext());
            }
          // fall through
          case 97: break;
          case 12:
            { return new Symbol(sym.DOSPTS, yyline, yycolumn,yytext());
            }
          // fall through
          case 98: break;
          case 13:
            { return new Symbol(sym.FINCADENA, yyline, yycolumn,yytext());
            }
          // fall through
          case 99: break;
          case 14:
            { return new Symbol(sym.MENOR, yyline, yycolumn,yytext());
            }
          // fall through
          case 100: break;
          case 15:
            { return new Symbol(sym.IGUAL, yyline, yycolumn,yytext());
            }
          // fall through
          case 101: break;
          case 16:
            { return new Symbol(sym.MAYOR, yyline, yycolumn,yytext());
            }
          // fall through
          case 102: break;
          case 17:
            { return new Symbol(sym.IDENTIFICADOR, yyline, yycolumn,yytext());
            }
          // fall through
          case 103: break;
          case 18:
            { return new Symbol(sym.CORCHEA, yyline, yycolumn,yytext());
            }
          // fall through
          case 104: break;
          case 19:
            { return new Symbol(sym.CORCHEC, yyline, yycolumn,yytext());
            }
          // fall through
          case 105: break;
          case 20:
            { return new Symbol(sym.LLAVEA, yyline, yycolumn,yytext());
            }
          // fall through
          case 106: break;
          case 21:
            { return new Symbol(sym.LLAVEC, yyline, yycolumn,yytext());
            }
          // fall through
          case 107: break;
          case 22:
            { return new Symbol(sym.AND, yyline, yycolumn,yytext());
            }
          // fall through
          case 108: break;
          case 23:
            { return new Symbol(sym.VALOR, yyline, yycolumn,yytext());
            }
          // fall through
          case 109: break;
          case 24:
            { return new Symbol(sym.ID, yyline, yycolumn,yytext());
            }
          // fall through
          case 110: break;
          case 25:
            { return new Symbol(sym.IF, yyline, yycolumn,yytext());
            }
          // fall through
          case 111: break;
          case 26:
            { return new Symbol(sym.OR, yyline, yycolumn,yytext());
            }
          // fall through
          case 112: break;
          case 27:
            { return new Symbol(sym.DECI, yyline, yycolumn,yytext());
            }
          // fall through
          case 113: break;
          case 28:
            { return new Symbol(sym.ALT, yyline, yycolumn,yytext());
            }
          // fall through
          case 114: break;
          case 29:
            { return new Symbol(sym.ASC, yyline, yycolumn,yytext());
            }
          // fall through
          case 115: break;
          case 30:
            { return new Symbol(sym.PARRA, yyline, yycolumn,yytext());
            }
          // fall through
          case 116: break;
          case 31:
            { return new Symbol(sym.END, yyline, yycolumn,yytext());
            }
          // fall through
          case 117: break;
          case 32:
            { return new Symbol(sym.SRC, yyline, yycolumn,yytext());
            }
          // fall through
          case 118: break;
          case 33:
            { return new Symbol(sym.CHAR, yyline, yycolumn,yytext());
            }
          // fall through
          case 119: break;
          case 34:
            { return new Symbol(sym.COLS, yyline, yycolumn,yytext());
            }
          // fall through
          case 120: break;
          case 35:
            { return new Symbol(sym.BR, yyline, yycolumn,yytext());
            }
          // fall through
          case 121: break;
          case 36:
            { return new Symbol(sym.CC, yyline, yycolumn,yytext());
            }
          // fall through
          case 122: break;
          case 37:
            { return new Symbol(sym.TITUH, yyline, yycolumn,yytext());
            }
          // fall through
          case 123: break;
          case 38:
            { return new Symbol(sym.DESC, yyline, yycolumn,yytext());
            }
          // fall through
          case 124: break;
          case 39:
            { return new Symbol(sym.ELSE, yyline, yycolumn,yytext());
            }
          // fall through
          case 125: break;
          case 40:
            { return new Symbol(sym.EXIT, yyline, yycolumn,yytext());
            }
          // fall through
          case 126: break;
          case 41:
            { return new Symbol(sym.HREF, yyline, yycolumn,yytext());
            }
          // fall through
          case 127: break;
          case 42:
            { return new Symbol(sym.INIT, yyline, yycolumn,yytext());
            }
          // fall through
          case 128: break;
          case 43:
            { return new Symbol(sym.NAME, yyline, yycolumn,yytext());
            }
          // fall through
          case 129: break;
          case 44:
            { return new Symbol(sym.ROWS, yyline, yycolumn,yytext());
            }
          // fall through
          case 130: break;
          case 45:
            { return new Symbol(sym.THEN, yyline, yycolumn,yytext());
            }
          // fall through
          case 131: break;
          case 46:
            { return new Symbol(sym.TRUE, yyline, yycolumn,yytext());
            }
          // fall through
          case 132: break;
          case 47:
            { return new Symbol(sym.TYPE, yyline, yycolumn,yytext());
            }
          // fall through
          case 133: break;
          case 48:
            { return new Symbol(sym.CLASS, yyline, yycolumn,yytext());
            }
          // fall through
          case 134: break;
          case 49:
            { return new Symbol(sym.COLOR, yyline, yycolumn,yytext());
            }
          // fall through
          case 135: break;
          case 50:
            { return new Symbol(sym.DIV, yyline, yycolumn,yytext());
            }
          // fall through
          case 136: break;
          case 51:
            { return new Symbol(sym.IMG, yyline, yycolumn,yytext());
            }
          // fall through
          case 137: break;
          case 52:
            { return new Symbol(sym.FALSE, yyline, yycolumn,yytext());
            }
          // fall through
          case 138: break;
          case 53:
            { return new Symbol(sym.WHILE, yyline, yycolumn,yytext());
            }
          // fall through
          case 139: break;
          case 54:
            { return new Symbol(sym.WIDTH, yyline, yycolumn,yytext());
            }
          // fall through
          case 140: break;
          case 55:
            { return new Symbol(sym.BODY, yyline, yycolumn,yytext());
            }
          // fall through
          case 141: break;
          case 56:
            { return new Symbol(sym.HEAD, yyline, yycolumn,yytext());
            }
          // fall through
          case 142: break;
          case 57:
            { return new Symbol(sym.LINK, yyline, yycolumn,yytext());
            }
          // fall through
          case 143: break;
          case 58:
            { return new Symbol(sym.SPAM, yyline, yycolumn,yytext());
            }
          // fall through
          case 144: break;
          case 59:
            { return new Symbol(sym.HEIGHT, yyline, yycolumn,yytext());
            }
          // fall through
          case 145: break;
          case 60:
            { return new Symbol(sym.HUNTIL, yyline, yycolumn,yytext());
            }
          // fall through
          case 146: break;
          case 61:
            { return new Symbol(sym.INSERT, yyline, yycolumn,yytext());
            }
          // fall through
          case 147: break;
          case 62:
            { return new Symbol(sym.LETPAR, yyline, yycolumn,yytext());
            }
          // fall through
          case 148: break;
          case 63:
            { return new Symbol(sym.REPEAT, yyline, yycolumn,yytext());
            }
          // fall through
          case 149: break;
          case 64:
            { return new Symbol(sym.STRING, yyline, yycolumn,yytext());
            }
          // fall through
          case 150: break;
          case 65:
            { return new Symbol(sym.BOOLEAN, yyline, yycolumn,yytext());
            }
          // fall through
          case 151: break;
          case 66:
            { return new Symbol(sym.INPUT, yyline, yycolumn,yytext());
            }
          // fall through
          case 152: break;
          case 67:
            { return new Symbol(sym.TITLE, yyline, yycolumn,yytext());
            }
          // fall through
          case 153: break;
          case 68:
            { return new Symbol(sym.DECIMAL, yyline, yycolumn,yytext());
            }
          // fall through
          case 154: break;
          case 69:
            { return new Symbol(sym.INTERGER, yyline, yycolumn,yytext());
            }
          // fall through
          case 155: break;
          case 70:
            { return new Symbol(sym.ONCLICK, yyline, yycolumn,yytext());
            }
          // fall through
          case 156: break;
          case 71:
            { return new Symbol(sym.REVERSE, yyline, yycolumn,yytext());
            }
          // fall through
          case 157: break;
          case 72:
            { return new Symbol(sym.BUTTON, yyline, yycolumn,yytext());
            }
          // fall through
          case 158: break;
          case 73:
            { return new Symbol(sym.OPTION, yyline, yycolumn,yytext());
            }
          // fall through
          case 159: break;
          case 74:
            { return new Symbol(sym.SELECT, yyline, yycolumn,yytext());
            }
          // fall through
          case 160: break;
          case 75:
            { return new Symbol(sym.LETIMPAR, yyline, yycolumn,yytext());
            }
          // fall through
          case 161: break;
          case 76:
            { return new Symbol(sym.REDIRECT, yyline, yycolumn,yytext());
            }
          // fall through
          case 162: break;
          case 77:
            { return new Symbol(sym.FONTSI, yyline, yycolumn,yytext());
            }
          // fall through
          case 163: break;
          case 78:
            { return new Symbol(sym.THENWHILE, yyline, yycolumn,yytext());
            }
          // fall through
          case 164: break;
          case 79:
            { return new Symbol(sym.ALEINF, yyline, yycolumn,yytext());
            }
          // fall through
          case 165: break;
          case 80:
            { return new Symbol(sym.BACKG, yyline, yycolumn,yytext());
            }
          // fall through
          case 166: break;
          case 81:
            { return new Symbol(sym.TEXTAREA, yyline, yycolumn,yytext());
            }
          // fall through
          case 167: break;
          case 82:
            { return new Symbol(sym.TEXTALI, yyline, yycolumn,yytext());
            }
          // fall through
          case 168: break;
          case 83:
            { return new Symbol(sym.SCRIPT, yyline, yycolumn,yytext());
            }
          // fall through
          case 169: break;
          case 84:
            { return new Symbol(sym.FONTFA, yyline, yycolumn,yytext());
            }
          // fall through
          case 170: break;
          case 85:
            { return new Symbol(sym.NUMALE, yyline, yycolumn,yytext());
            }
          // fall through
          case 171: break;
          case 86:
            { return new Symbol(sym.CARALE, yyline, yycolumn,yytext());
            }
          // fall through
          case 172: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
