
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package main.analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IDENTIFICADOR = 100;
  public static final int family = 93;
  public static final int LETIMPAR = 62;
  public static final int TYPE = 48;
  public static final int ROWS = 52;
  public static final int ASC = 59;
  public static final int MAYOR = 10;
  public static final int NAME = 50;
  public static final int DIVI = 12;
  public static final int INIT = 76;
  public static final int ALT = 57;
  public static final int enlace = 90;
  public static final int ELIF = 82;
  public static final int POR = 11;
  public static final int INTEGER = 69;
  public static final int DIFER = 15;
  public static final int TITUH = 39;
  public static final int FALSE = 75;
  public static final int ELEMENT = 87;
  public static final int THENWHILE = 86;
  public static final int THEN = 80;
  public static final int DECI = 99;
  public static final int WIDTH = 55;
  public static final int ALEINF = 66;
  public static final int REVERSE = 63;
  public static final int size = 92;
  public static final int DOSPTS = 21;
  public static final int NUMALE = 65;
  public static final int PARRA = 40;
  public static final int CLASS = 53;
  public static final int SELECT = 33;
  public static final int TEXTAREA = 32;
  public static final int REDIRECT = 68;
  public static final int COMA = 23;
  public static final int ENTERO = 98;
  public static final int HUNTIL = 84;
  public static final int TRUE = 74;
  public static final int IGUAL = 7;
  public static final int PAR2 = 3;
  public static final int PAR1 = 2;
  public static final int WHILE = 85;
  public static final int COLS = 51;
  public static final int CHAR = 73;
  public static final int DECIMAL = 72;
  public static final int BOOLEAN = 70;
  public static final int LETPAR = 61;
  public static final int INPUT = 31;
  public static final int DIV = 35;
  public static final int ELSE = 81;
  public static final int MENOS = 5;
  public static final int MENOR = 9;
  public static final int MAS = 4;
  public static final int LOAD = 89;
  public static final int BACKG = 43;
  public static final int th = 97;
  public static final int LINK = 28;
  public static final int EOF = 0;
  public static final int FONTSI = 46;
  public static final int TEXTALI = 47;
  public static final int BUTTON = 38;
  public static final int CARALE = 64;
  public static final int REPEAT = 83;
  public static final int SPAM = 30;
  public static final int SCRIPT = 41;
  public static final int SRC = 54;
  public static final int COMIS = 24;
  public static final int BODY = 29;
  public static final int HREF = 42;
  public static final int TITLE = 27;
  public static final int tipos = 95;
  public static final int OR = 13;
  public static final int error = 1;
  public static final int EXIT = 67;
  public static final int CC = 25;
  public static final int IF = 79;
  public static final int FINCADENA = 16;
  public static final int DESC = 60;
  public static final int ID = 49;
  public static final int COLOR = 44;
  public static final int FONTFA = 45;
  public static final int HEAD = 26;
  public static final int END = 77;
  public static final int COMID = 22;
  public static final int UMENOS = 6;
  public static final int IMG = 36;
  public static final int VALOR = 101;
  public static final int aling = 94;
  public static final int HEIGHT = 56;
  public static final int BR = 37;
  public static final int GLOBAL = 88;
  public static final int OPTION = 34;
  public static final int CORCHEC = 20;
  public static final int INSERT = 78;
  public static final int STRING = 71;
  public static final int CORCHEA = 19;
  public static final int ONCLICK = 58;
  public static final int clase = 96;
  public static final int AND = 14;
  public static final int LLAVEC = 18;
  public static final int LLAVEA = 17;
  public static final int EQUALS = 8;
  public static final int colo = 91;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PAR1",
  "PAR2",
  "MAS",
  "MENOS",
  "UMENOS",
  "IGUAL",
  "EQUALS",
  "MENOR",
  "MAYOR",
  "POR",
  "DIVI",
  "OR",
  "AND",
  "DIFER",
  "FINCADENA",
  "LLAVEA",
  "LLAVEC",
  "CORCHEA",
  "CORCHEC",
  "DOSPTS",
  "COMID",
  "COMA",
  "COMIS",
  "CC",
  "HEAD",
  "TITLE",
  "LINK",
  "BODY",
  "SPAM",
  "INPUT",
  "TEXTAREA",
  "SELECT",
  "OPTION",
  "DIV",
  "IMG",
  "BR",
  "BUTTON",
  "TITUH",
  "PARRA",
  "SCRIPT",
  "HREF",
  "BACKG",
  "COLOR",
  "FONTFA",
  "FONTSI",
  "TEXTALI",
  "TYPE",
  "ID",
  "NAME",
  "COLS",
  "ROWS",
  "CLASS",
  "SRC",
  "WIDTH",
  "HEIGHT",
  "ALT",
  "ONCLICK",
  "ASC",
  "DESC",
  "LETPAR",
  "LETIMPAR",
  "REVERSE",
  "CARALE",
  "NUMALE",
  "ALEINF",
  "EXIT",
  "REDIRECT",
  "INTEGER",
  "BOOLEAN",
  "STRING",
  "DECIMAL",
  "CHAR",
  "TRUE",
  "FALSE",
  "INIT",
  "END",
  "INSERT",
  "IF",
  "THEN",
  "ELSE",
  "ELIF",
  "REPEAT",
  "HUNTIL",
  "WHILE",
  "THENWHILE",
  "ELEMENT",
  "GLOBAL",
  "LOAD",
  "enlace",
  "colo",
  "size",
  "family",
  "aling",
  "tipos",
  "clase",
  "th",
  "ENTERO",
  "DECI",
  "IDENTIFICADOR",
  "VALOR"
  };
}

