
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package main.analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IDENTIFICADOR = 96;
  public static final int family = 89;
  public static final int LETIMPAR = 60;
  public static final int TYPE = 46;
  public static final int ROWS = 50;
  public static final int ASC = 57;
  public static final int MAYOR = 10;
  public static final int NAME = 48;
  public static final int DIVI = 12;
  public static final int INIT = 74;
  public static final int ALT = 55;
  public static final int enlace = 86;
  public static final int POR = 11;
  public static final int INTEGER = 67;
  public static final int DIFER = 15;
  public static final int TITUH = 37;
  public static final int FALSE = 73;
  public static final int ELEMENT = 84;
  public static final int THENWHILE = 83;
  public static final int THEN = 78;
  public static final int DECI = 95;
  public static final int WIDTH = 53;
  public static final int ALEINF = 64;
  public static final int REVERSE = 61;
  public static final int size = 88;
  public static final int DOSPTS = 21;
  public static final int NUMALE = 63;
  public static final int PARRA = 38;
  public static final int CLASS = 51;
  public static final int SELECT = 31;
  public static final int TEXTAREA = 30;
  public static final int REDIRECT = 66;
  public static final int ENTERO = 94;
  public static final int HUNTIL = 81;
  public static final int TRUE = 72;
  public static final int IGUAL = 7;
  public static final int PAR2 = 3;
  public static final int PAR1 = 2;
  public static final int WHILE = 82;
  public static final int COLS = 49;
  public static final int CHAR = 71;
  public static final int DECIMAL = 70;
  public static final int BOOLEAN = 68;
  public static final int LETPAR = 59;
  public static final int INPUT = 29;
  public static final int DIV = 33;
  public static final int ELSE = 79;
  public static final int MENOS = 5;
  public static final int MENOR = 9;
  public static final int MAS = 4;
  public static final int BACKG = 41;
  public static final int th = 93;
  public static final int LINK = 26;
  public static final int EOF = 0;
  public static final int FONTSI = 44;
  public static final int TEXTALI = 45;
  public static final int BUTTON = 36;
  public static final int CARALE = 62;
  public static final int REPEAT = 80;
  public static final int SPAM = 28;
  public static final int SCRIPT = 39;
  public static final int SRC = 52;
  public static final int BODY = 27;
  public static final int HREF = 40;
  public static final int TITLE = 25;
  public static final int tipos = 91;
  public static final int OR = 13;
  public static final int error = 1;
  public static final int EXIT = 65;
  public static final int CC = 23;
  public static final int IF = 77;
  public static final int FINCADENA = 16;
  public static final int DESC = 58;
  public static final int ID = 47;
  public static final int COLOR = 42;
  public static final int FONTFA = 43;
  public static final int HEAD = 24;
  public static final int END = 75;
  public static final int COMID = 22;
  public static final int UMENOS = 6;
  public static final int IMG = 34;
  public static final int VALOR = 97;
  public static final int aling = 90;
  public static final int HEIGHT = 54;
  public static final int BR = 35;
  public static final int GLOBAL = 85;
  public static final int OPTION = 32;
  public static final int CORCHEC = 20;
  public static final int INSERT = 76;
  public static final int STRING = 69;
  public static final int CORCHEA = 19;
  public static final int ONCLICK = 56;
  public static final int clase = 92;
  public static final int AND = 14;
  public static final int LLAVEC = 18;
  public static final int LLAVEA = 17;
  public static final int EQUALS = 8;
  public static final int colo = 87;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PAR1",
  "PAR2",
  "MAS",
  "MENOS",
  "UMENOS",
  "IGUAL",
  "EQUALS",
  "MENOR",
  "MAYOR",
  "POR",
  "DIVI",
  "OR",
  "AND",
  "DIFER",
  "FINCADENA",
  "LLAVEA",
  "LLAVEC",
  "CORCHEA",
  "CORCHEC",
  "DOSPTS",
  "COMID",
  "CC",
  "HEAD",
  "TITLE",
  "LINK",
  "BODY",
  "SPAM",
  "INPUT",
  "TEXTAREA",
  "SELECT",
  "OPTION",
  "DIV",
  "IMG",
  "BR",
  "BUTTON",
  "TITUH",
  "PARRA",
  "SCRIPT",
  "HREF",
  "BACKG",
  "COLOR",
  "FONTFA",
  "FONTSI",
  "TEXTALI",
  "TYPE",
  "ID",
  "NAME",
  "COLS",
  "ROWS",
  "CLASS",
  "SRC",
  "WIDTH",
  "HEIGHT",
  "ALT",
  "ONCLICK",
  "ASC",
  "DESC",
  "LETPAR",
  "LETIMPAR",
  "REVERSE",
  "CARALE",
  "NUMALE",
  "ALEINF",
  "EXIT",
  "REDIRECT",
  "INTEGER",
  "BOOLEAN",
  "STRING",
  "DECIMAL",
  "CHAR",
  "TRUE",
  "FALSE",
  "INIT",
  "END",
  "INSERT",
  "IF",
  "THEN",
  "ELSE",
  "REPEAT",
  "HUNTIL",
  "WHILE",
  "THENWHILE",
  "ELEMENT",
  "GLOBAL",
  "enlace",
  "colo",
  "size",
  "family",
  "aling",
  "tipos",
  "clase",
  "th",
  "ENTERO",
  "DECI",
  "IDENTIFICADOR",
  "VALOR"
  };
}

