
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package main.analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IDENTIFICADOR = 84;
  public static final int LETIMPAR = 58;
  public static final int TYPE = 44;
  public static final int ROWS = 48;
  public static final int ASC = 55;
  public static final int MAYOR = 8;
  public static final int NAME = 46;
  public static final int DIVI = 10;
  public static final int INIT = 72;
  public static final int ALT = 53;
  public static final int POR = 9;
  public static final int DIFER = 13;
  public static final int TITUH = 35;
  public static final int FALSE = 71;
  public static final int THENWHILE = 81;
  public static final int THEN = 76;
  public static final int DECI = 83;
  public static final int WIDTH = 51;
  public static final int ALEINF = 62;
  public static final int REVERSE = 59;
  public static final int DOSPTS = 19;
  public static final int NUMALE = 61;
  public static final int PARRA = 36;
  public static final int CLASS = 49;
  public static final int SELECT = 29;
  public static final int TEXTAREA = 28;
  public static final int REDIRECT = 64;
  public static final int ENTERO = 82;
  public static final int HUNTIL = 79;
  public static final int TRUE = 70;
  public static final int IGUAL = 6;
  public static final int PAR2 = 3;
  public static final int PAR1 = 2;
  public static final int WHILE = 80;
  public static final int COLS = 47;
  public static final int DECIMAL = 68;
  public static final int CHAR = 69;
  public static final int BOOLEAN = 66;
  public static final int LETPAR = 57;
  public static final int INPUT = 27;
  public static final int INTERGER = 65;
  public static final int DIV = 31;
  public static final int ELSE = 77;
  public static final int MENOS = 5;
  public static final int MENOR = 7;
  public static final int MAS = 4;
  public static final int BACKG = 39;
  public static final int LINK = 24;
  public static final int EOF = 0;
  public static final int FONTSI = 42;
  public static final int TEXTALI = 43;
  public static final int BUTTON = 34;
  public static final int CARALE = 60;
  public static final int REPEAT = 78;
  public static final int SPAM = 26;
  public static final int SCRIPT = 37;
  public static final int SRC = 50;
  public static final int BODY = 25;
  public static final int HREF = 38;
  public static final int TITLE = 23;
  public static final int OR = 11;
  public static final int error = 1;
  public static final int EXIT = 63;
  public static final int CC = 21;
  public static final int IF = 75;
  public static final int FINCADENA = 14;
  public static final int DESC = 56;
  public static final int ID = 45;
  public static final int COLOR = 40;
  public static final int FONTFA = 41;
  public static final int HEAD = 22;
  public static final int END = 73;
  public static final int COMID = 20;
  public static final int IMG = 32;
  public static final int VALOR = 85;
  public static final int HEIGHT = 52;
  public static final int BR = 33;
  public static final int OPTION = 30;
  public static final int CORCHEC = 18;
  public static final int INSERT = 74;
  public static final int STRING = 67;
  public static final int CORCHEA = 17;
  public static final int ONCLICK = 54;
  public static final int AND = 12;
  public static final int LLAVEC = 16;
  public static final int LLAVEA = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PAR1",
  "PAR2",
  "MAS",
  "MENOS",
  "IGUAL",
  "MENOR",
  "MAYOR",
  "POR",
  "DIVI",
  "OR",
  "AND",
  "DIFER",
  "FINCADENA",
  "LLAVEA",
  "LLAVEC",
  "CORCHEA",
  "CORCHEC",
  "DOSPTS",
  "COMID",
  "CC",
  "HEAD",
  "TITLE",
  "LINK",
  "BODY",
  "SPAM",
  "INPUT",
  "TEXTAREA",
  "SELECT",
  "OPTION",
  "DIV",
  "IMG",
  "BR",
  "BUTTON",
  "TITUH",
  "PARRA",
  "SCRIPT",
  "HREF",
  "BACKG",
  "COLOR",
  "FONTFA",
  "FONTSI",
  "TEXTALI",
  "TYPE",
  "ID",
  "NAME",
  "COLS",
  "ROWS",
  "CLASS",
  "SRC",
  "WIDTH",
  "HEIGHT",
  "ALT",
  "ONCLICK",
  "ASC",
  "DESC",
  "LETPAR",
  "LETIMPAR",
  "REVERSE",
  "CARALE",
  "NUMALE",
  "ALEINF",
  "EXIT",
  "REDIRECT",
  "INTERGER",
  "BOOLEAN",
  "STRING",
  "DECIMAL",
  "CHAR",
  "TRUE",
  "FALSE",
  "INIT",
  "END",
  "INSERT",
  "IF",
  "THEN",
  "ELSE",
  "REPEAT",
  "HUNTIL",
  "WHILE",
  "THENWHILE",
  "ENTERO",
  "DECI",
  "IDENTIFICADOR",
  "VALOR"
  };
}

